name: Production CI/CD

# main branch push 시
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # pm2 정지 및 삭제
            pm2 stop blog-frontend
            pm2 delete blog-frontend

            git clone git@github.com:JongDeug/blog-frontend.git blog-frontend-v2

            cd blog-frontend-v2

            > .env
            echo "PUBLIC_API_URL=${{ vars.PUBLIC_API_URL }}" >> .env

            pnpm run build

            pm2 start build/index.js --name blog-frontend
